export const CREATOR_OS_URL = 'https://creatorai-os.vercel.app'
export const PROMPT_ARCHITECT_URL = 'https://prompt-architect-gules.vercel.app'
export const MANUSCRIPT_STUDIO_URL = 'https://manuscript-studio-os.com'
export const PARTNER_EMAIL = 'mailto:matt@sovereignshieldtechnologies.com'
export const FORMSPREE_ENDPOINT = 'https://formspree.io/f/xeevodzl'
